project_id = "mtmroennrczdcaasrilw"

[functions.send-contact-email]
verify_jwt = false

[functions.claude]
verify_jwt = false

[functions.deploy-to-cloudflare]
verify_jwt = true

[functions.html-to-react]
verify_jwt = true

[functions.ai-generate]
verify_jwt = true