project_id = "mtmroennrczdcaasrilw"

[functions.send-contact-email]
verify_jwt = false

[functions.claude]
verify_jwt = false

[functions.deploy-to-netlify]
verify_jwt = true

[functions.html-to-react]
verify_jwt = true

[functions.ai-generate]
verify_jwt = false

[functions.generate-site]
verify_jwt = true

[functions.modify-site]
verify_jwt = true

[functions.generate-screenshot]
verify_jwt = true

[functions.claude-stream]
verify_jwt = false

[functions.get-analytics]
verify_jwt = true

[functions.migrate-to-magellan]
verify_jwt = true