project_id = "mtmroennrczdcaasrilw"

[functions.send-contact-email]
verify_jwt = false

[functions.generate-site]
verify_jwt = true

[functions.modify-site]
verify_jwt = true

[functions.generate-screenshot]
verify_jwt = true

[functions.generate-project-name]
verify_jwt = true

[functions.chat-only]
verify_jwt = true

[functions.memory]
verify_jwt = true

[functions.unified-modify]
verify_jwt = true

[functions.generate-invoice]
verify_jwt = true

[functions.domain-connect-discover]
verify_jwt = true

[functions.domain-connect-verify]
verify_jwt = true

[functions.publish-project]
verify_jwt = true

[functions.generate-crm]
verify_jwt = true

[functions.generate-widget]
verify_jwt = true

[functions.import-google-sheets]
verify_jwt = true

[functions.import-from-database]
verify_jwt = true

[functions.publish-to-netlify]
verify_jwt = true

[functions.preview-sandbox]
verify_jwt = true

[functions.close-sandbox]
verify_jwt = true

[functions.update-sandbox]
verify_jwt = true
