project_id = "mtmroennrczdcaasrilw"

[functions.deploy-worker]
verify_jwt = true

[functions.publish-to-kv]
verify_jwt = true

[functions.generate-embeddings]
verify_jwt = true

[functions.send-contact-email]
verify_jwt = false

[functions.claude]
verify_jwt = false

[functions.deploy-to-cloudflare]
verify_jwt = true

[functions.html-to-react]
verify_jwt = true

[functions.ai-generate]
verify_jwt = false

[functions.generate-site]
verify_jwt = true

[functions.modify-site]
verify_jwt = true

[functions.generate-screenshot]
verify_jwt = true

[functions.claude-stream]
verify_jwt = false

[functions.get-analytics]
verify_jwt = true

[functions.agent]
verify_jwt = true

[functions.generate-project-name]
verify_jwt = true

[functions.get-cloudflare-analytics]
verify_jwt = true

[functions.add-custom-domain]
verify_jwt = true